query_select_revenue_by_month = \
    ("WITH sales AS "
     "(SELECT YEAR(sale.sale_date) AS year, "
     "MONTH(sale.sale_date) AS month, "
     "COALESCE(SUM(product.product_price * selling.sale_quantity),0) AS turnover "
     "FROM db_sales.sale "
     "LEFT JOIN db_sales.selling ON sale.sale_id = selling.sale_id "
     "LEFT JOIN db_sales.product ON selling.product_id = product.product_id "
     "GROUP BY year, month), "
     "expenses AS "
     "(SELECT YEAR(purchase.purchase_date) AS year, "
     "MONTH(purchase.purchase_date) AS month, "
     "COALESCE(SUM(purchasing.purchase_price * purchasing.purchase_quantity),0) AS expenses "
     "FROM db_sales.purchase "
     "LEFT JOIN db_sales.purchasing ON purchase.purchase_id = purchasing.purchase_id "
     "LEFT JOIN db_sales.product ON purchasing.product_id = product.product_id "
     "GROUP BY year, month) "
     "SELECT sales.year AS year, sales.month AS month, "
     "COALESCE(sales.turnover, 0) AS turnover, "
     "COALESCE(expenses.expenses, 0) AS expenses, "
     "COALESCE(sales.turnover, 0) - COALESCE(expenses.expenses, 0) AS recipes "
     "FROM sales "
     "LEFT JOIN expenses ON sales.month = expenses.month AND sales.year = expenses.year "
     "ORDER BY year, month;")


query_select_revenue_by_year = \
    ("WITH sales AS "
     "(SELECT YEAR(sale.sale_date) AS year, "
     "COALESCE(SUM(product.product_price * selling.sale_quantity),0) AS turnover "
     "FROM db_sales.sale "
     "LEFT JOIN db_sales.selling ON sale.sale_id = selling.sale_id "
     "LEFT JOIN db_sales.product ON selling.product_id = product.product_id "
     "GROUP BY year), "
     "expenses AS "
     "(SELECT YEAR(purchase.purchase_date) AS year, "
     "COALESCE(SUM(purchasing.purchase_price * purchasing.purchase_quantity),0) AS expenses "
     "FROM db_sales.purchase "
     "LEFT JOIN db_sales.purchasing ON purchase.purchase_id = purchasing.purchase_id "
     "LEFT JOIN db_sales.product ON purchasing.product_id = product.product_id "
     "GROUP BY year) "
     "SELECT sales.year AS year, "
     "COALESCE(sales.turnover, 0) AS turnover, "
     "COALESCE(expenses.expenses, 0) AS expenses, "
     "COALESCE(sales.turnover, 0) - COALESCE(expenses.expenses, 0) AS recipes "
     "FROM sales "
     "LEFT JOIN expenses ON sales.year = expenses.year "
     "ORDER BY year;")